wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.8
    start_time: 1643981018
    t:
      1:
      - 1
      - 3
      2:
      - 1
      - 3
      3:
      - 13
      4: 3.8.8
      5: 0.12.10
      8:
      - 2
      - 5
